[package]
name = "cpu-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-absolutize = "3.1.1"
rand = "0.8.5"
text_io = "0.1.12"
